name: cljminecraft
main: cljminecraft.ClojurePlugin
version: 1.0.6
website: https://github.com/CmdrDats/clj-minecraft
author: CmdrDats & aiscott
description: Bukkit + clojure integration library
commands:
  clj.repl:
    description: Start or stop the Clojure REPL
    permission: clojure.repl
    usage: |
      /<command> start/stop [port]
      Example: /<command> start - starts a REPL on the default 4005 port
      Example: /<command> start 5006 - starts a REPL on the 5006 port
      Example: /<command> stop - stop the current REPL
  clj.tabtest:
    description: Just a test of the tabcompletion
    permission: clojure.tabtest
    usage: /<command> player material (start|stop) tab-reverse-of-player-name
  clj.addevent:
    description: Get notified on event
    permission: clojure.event
    usage: /<command> eventname message
  clj.spawnentity:
    description: Spawn a given entity in front of you
    permission: clojure.spawn
    usage: /<command> entityname
  clj.permission:
    description: Set a permission for a given player
    permission: clojure.permission
    usage: /<command> player permissionname (allow|disallow|release)
